nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: false
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['^https?://.*?$', 'https://localhost:8080', 'http://localhost:8081', '*', http://192.168.0.102:8081']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['Content-Type', 'Authorization']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~
        '^/api': ~