<?php

namespace App\Repository;

use App\Entity\Opcion;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * OpcionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Opcion::class);
    }

    public function findByPropiedadItem($propiedadItem, $term)
    {
        return $this->createQueryBuilder('o')
            ->join('o.item', 'i')
            ->join('i.propiedadItems', 'pi')
            ->where('pi.id = :id')
            ->andWhere('o.nombre LIKE :term')
            ->setParameter('id', $propiedadItem)
            ->setParameter('term', '%'.$term.'%')
            ->getQuery()
            ->getResult()
        ;
    }
}
