<?php

namespace App\Repository;

use App\Entity\Resultado;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * ResultadoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Resultado::class);
    }

    public function findByModulo($modulos, $formularioId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('a');

        $qb->select('a')
            ->from('SistemaFormularioBundle:Resultado', 'a')
            ->join('a.propiedadItem', 'pi')
            ->join('pi.modulo', 'm')
            ->join('a.formularioResultado', 'fr')
            ->join('fr.usuarioFormulario', 'uf')
            ->join('uf.formulario', 'f')
            ->where('m.id in (:modulos)')
            ->andWhere('f.id = :formularioId')
            ->setParameter('modulos', $modulos)
            ->setParameter('formularioId', $formularioId)
        ;

        return $qb->getQuery()->getResult();
    }
}
