easy_admin:
    site_name: '<img src="/images/hogarLogo.png" style="height: 61px;" />'
#     formats:
#         date: 'd/m/Y'
#         time: 'H:i'
#         datetime: 'd/m/Y H:i:s'
#         number: '%.2f'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: false }
            - { name: 'delete', icon: 'remove', label: false }
            - { name: 'show', icon: 'search', label: false }
