easy_admin:
    design:
        assets:
            css:
                - 'css/admin.css'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'
        templates:
            layout: 'easy_admin/layout.html.twig'
        menu:
            - { label: 'Gestión de Trabajo' , permission: [ROLE_ADMIN, ROLE_ORDEN_TRABAJO, ROLE_SOLICITUD, ROLE_CARPETA, ROLE_DASHBOARD] }
            - { label: 'Dashboard', route: 'dashboard', icon: 'dashboard', permission: [ROLE_ADMIN, ROLE_DASHBOARD] }
            - { entity: 'OrdenTrabajo', label: 'Ordenes Trabajo', icon: 'briefcase', default: true, permission: [ROLE_ORDEN_TRABAJO] }
            - { entity: 'Solicitud', label: 'Solicitudes', icon: 'list', permission: [ROLE_SOLICITUD] }
            - { entity: 'Carpeta', label: 'Carpetas', icon: 'folder', permission: [ROLE_CARPETA] }
            - { entity: 'Equipo', label: 'Equipos', icon: 'server', permission: [ROLE_ORDEN_TRABAJO, ROLE_CLIENTE_CRUD] }
            - { entity: 'FormularioResultadoExpress', label: 'Formularios Express', icon: 'business-time' }
            - { entity: 'formularioCompraMateriales', label: 'Compra de materiales', icon: 'shopping-cart' }
            - label: 'Papelera'
              icon: 'trash-alt' 
              children:
                - { entity: 'RecycleOrdenTrabajo', label: 'Ordenes Trabajo', icon: 'briefcase', default: true, permission: [ROLE_ORDEN_TRABAJO] }
                - { entity: 'RecycleSolicitud', label: 'Solicitudes', icon: 'list', permission: [ROLE_SOLICITUD] }
                - { entity: 'RecycleUser', label: 'Users', icon: 'user', permission: [ROLE_USER_CRUD] }
                - { entity: 'RecycleCliente', label: 'Clientes', icon: 'user', permission: [ROLE_CLIENTE_CRUD] }
                - { entity: 'RecycleGroup', label: 'Groups', icon: 'users', permission: [ROLE_GROUP] }
                - { entity: 'RecycleServicio', label: 'Servicios', icon: 'paper-plane', permission: [ROLE_SERVICIO] }
                - { entity: 'RecycleSucursal', label: 'Sucursales', icon: 'building', permission: [ROLE_SUCURSAL] }
                - { entity: 'RecyclePais', label: 'Países', icon: 'globe-americas', permission: [ROLE_PAIS] }
                - { entity: 'RecycleFormulario', label: 'Formularios', icon: 'align-justify', permission: [ ROLE_FORMULARIO ] }
                - { entity: 'RecycleModulo', label: 'Modulos', icon: 'boxes', permission: [ROLE_MODULO] }
                - { entity: 'RecycleItem', label: 'Items', icon: 'pager', permission: [ROLE_ITEM] }
            - { label: 'Administrador', permission: [ROLE_USER_CRUD, ROLE_CLIENTE_CRUD, ROLE_GROUP, ROLE_SERVICIO, ROLE_SUCURSAL,ROLE_PAIS ]  }
            - { entity: 'User', label: 'Users', icon: 'user', permission: [ROLE_USER_CRUD] }
            - { entity: 'Cliente', label: 'Clientes', icon: 'user', permission: [ROLE_CLIENTE_CRUD] }
            - { entity: 'Group', label: 'Groups', icon: 'users', permission: [ROLE_GROUP] }
            - { entity: 'Servicio', label: 'Servicios', icon: 'paper-plane', permission: [ROLE_SERVICIO] }
            - { entity: 'Sucursal', label: 'Sucursales', icon: 'building', permission: [ROLE_SUCURSAL] }
            - { entity: 'Pais', label: 'Países', icon: 'globe-americas', permission: [ROLE_PAIS] }

            - { label: 'Formularios', permission: [ROLE_FORMULARIO, ROLE_MODULO, ROLE_ITEM ]   }
            - { entity: 'Formulario', label: 'Formularios', icon: 'align-justify', permission: [ ROLE_FORMULARIO ] }
            - { entity: 'Modulo', label: 'Modulos', icon: 'boxes', permission: [ROLE_MODULO] }
            - { entity: 'Item', label: 'Items', icon: 'pager', permission: [ROLE_ITEM] }

            - { label: 'Otros', permission: [ROLE_SUPER_ADMIN]   }
            - { entity: 'Client', icon: 'walking', permission: [ROLE_SUPER_ADMIN] }

            # - { entity: 'SolicitudCliente', icon: 'boxes', permission: [ROLE_CLIENTE_MENU] }
