easy_admin:
    design:
        assets:
            css:
                - 'css/admin.css'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'
        templates:
            layout: 'easy_admin/layout.html.twig'
        menu:
            - { label: 'Gestión de Trabajo' , permission: [ROLE_ADMIN, ROLE_ENCARGADO, ROLE_ENCARGADO, ROLE_ADMIN, ROLE_DASHBOARD, ROLE_STAFF, ROLE_EMPLEADO, ROLE_FACILITY, ROLE_MANAGER] }
            - { label: 'Dashboard', route: 'dashboard', icon: 'dashboard', permission: [ROLE_ADMIN, ROLE_DASHBOARD] }
            - { entity: 'OrdenTrabajo', label: 'Ordenes Trabajo', icon: 'briefcase', permission: [ROLE_SUCURSAL, ROLE_ADMIN] }
            - { entity: 'OrdenTrabajoCliente', label: 'Ordenes Trabajo', icon: 'briefcase', permission: [ROLE_STAFF, ROLE_FACILITY , ROLE_MANAGER] }
            - { entity: 'Solicitud', label: 'Solicitudes',default: true, icon: 'list', permission: [ROLE_ENCARGADO, ROLE_STAFF, ROLE_FACILITY, ROLE_MANAGER] }
            - { entity: 'Carpeta', label: 'Carpetas', icon: 'folder', permission: [ROLE_ADMIN]}
            - { entity: 'Equipo', label: 'Equipos', icon: 'server', permission: [ROLE_ENCARGADO, ROLE_ADMIN] }
            - { entity: 'FormularioResultadoExpress', permission: [ROLE_ADMIN, ROLE_SUCURSAL] , label: 'Formularios Express', icon: 'business-time'}
            - { entity: 'formularioCompraMateriales', label: 'Compra de materiales', icon: 'shopping-cart', permission: [ROLE_ADMIN,ROLE_SUCURSAL] }
            - label: 'Papelera'
              icon: 'trash-alt' 
              permission: [ROLE_ADMIN, ROLE_ENCARGADO ]
              children:
                - { entity: 'RecycleOrdenTrabajo', label: 'Ordenes Trabajo', icon: 'briefcase', default: true, permission: [ROLE_ENCARGADO] }
                - { entity: 'RecycleSolicitud', label: 'Solicitudes', icon: 'list', permission: [ROLE_ENCARGADO, ROLE_STAFF, ROLE_FACILITY, ROLE_MANAGER] }
                - { entity: 'RecycleUser', label: 'Users', icon: 'user', permission: [ROLE_ADMIN] }
                - { entity: 'RecycleCliente', label: 'Clientes', icon: 'user', permission: [ROLE_ADMIN] }
                - { entity: 'RecycleGroup', label: 'Groups', icon: 'users', permission: [ROLE_ADMIN] }
                - { entity: 'RecycleServicio', label: 'Servicios', icon: 'paper-plane', permission: [ROLE_ENCARGADO] }
                - { entity: 'RecycleSucursal', label: 'Sucursales', icon: 'building', permission: [ROLE_SUCURSAL] }
                - { entity: 'RecyclePais', label: 'Países', icon: 'globe-americas', permission: [ROLE_ADMIN] }
                - { entity: 'RecycleFormulario', label: 'Formularios', icon: 'align-justify', permission: [ ROLE_ADMIN ] }
                - { entity: 'RecycleModulo', label: 'Modulos', icon: 'boxes', permission: [ROLE_ADMIN] }
                - { entity: 'RecycleItem', label: 'Items', icon: 'pager', permission: [ROLE_ADMIN] }
            - { label: 'Administrador', permission: [ROLE_ADMIN, ROLE_ADMIN, ROLE_ADMIN, ROLE_ENCARGADO, ROLE_SUCURSAL,ROLE_ADMIN, ROLE_CLIENTE ]  }
            - { entity: 'User', label: 'Users', icon: 'user', permission: [ROLE_ADMIN] }
            - { entity: 'Cliente', label: 'Clientes', icon: 'user', permission: [ROLE_ADMIN] }
            - { entity: 'Group', label: 'Groups', icon: 'users', permission: [ROLE_ADMIN] }
            - { entity: 'Servicio', label: 'Servicios', icon: 'paper-plane', permission: [ROLE_ENCARGADO] }
            - { entity: 'Sucursal', label: 'Sucursales', icon: 'building', permission: [ROLE_ADMIN] }
            - { entity: 'Pais', label: 'Países', icon: 'globe-americas', permission: [ROLE_ADMIN] }
            - { entity: 'facilityCliente', label: ' Facility', icon: 'user', permission: [ROLE_MANAGER] }
            - { entity: 'UserCliente', label: 'Datos de Usuario', icon: 'user', permission: [ROLE_STAFF, ROLE_FACILITY, ROLE_MANAGER] }
            - { entity: 'sucursaldecliente', label: 'Datos de Sucursal', icon: 'building', permission: [ROLE_MANAGER, ROLE_FACILITY] }
            -  label: 'Opciones de Clientes'
               icon: 'folder'
               permission: ROLE_ADMIN   
               children:
                - { entity: 'Facility', label: 'Crear Facility', icon: 'user', permission: [ROLE_ADMIN] }
                - { entity: 'SucursalDeCliente', label: 'Datos de Sucursal', icon: 'building', permission: [ROLE_ADMIN] }

            - { label: 'Formularios', permission: [ROLE_ADMIN, ROLE_ADMIN, ROLE_ADMIN ]   }
            - { entity: 'Formulario', label: 'Formularios', icon: 'align-justify', permission: [ ROLE_ADMIN ] }
            - { entity: 'Modulo', label: 'Modulos', icon: 'boxes', permission: [ROLE_ADMIN] }
            - { entity: 'Item', label: 'Items', icon: 'pager', permission: [ROLE_ADMIN] }

            - { label: 'Otros', permission: [ROLE_SUPER_ADMIN]   }
            - { entity: 'Client', icon: 'walking', permission: [ROLE_SUPER_ADMIN] }

            # - { entity: 'SolicitudCliente', icon: 'boxes', permission: [ROLE_CLIENTE_MENU] }
