easy_admin:
    entities:
        CarpetaCliente:
            class: App\Entity\Cliente
            templates:
                # Twig namespace template syntax
                list: 'Carpeta/carpetaClientes.html.twig'
            list:
                item_permission: [ROLE_ADMIN,ROLE_CLIENTE]
                fields:
                    - 'id'
                    - 'apellido'
                    - 'nombre'
                    - 'razonSocial'
                    - 'sucursal'
                    - 'ivaConditionString'
