easy_admin:
    entities:
        ClienteSucursal:
            class: App\Entity\ClienteSucursal
            #controller: App\Controller\ClienteController
            #templates:
                # Twig namespace template syntax
                #new: 'Cliente/new.html.twig'
                #edit: 'Cliente/edit.html.twig'
                #new_ajax: 'Cliente/new_ajax.html.twig'
            list:
                #item_permission: [ROLE_CLIENTE_CRUD]
                #fields:
            edit:
                #item_permission: [ROLE_CLIENTE_CRUD]
            new:
                #item_permission: [ROLE_CLIENTE_CRUD]
            show:
                #item_permission: [ROLE_CLIENTE_CRUD]
            delete:
                #item_permission: [ROLE_CLIENTE_CRUD]
            search:
                #item_permission: [ROLE_CLIENTE_CRUD]