easy_admin:
    entities:
        ClienteSucursal:
            class: App\Entity\ClienteSucursal
            list:
                item_permission: [ROLE_SUCURSAL]
            edit:
                item_permission: [ROLE_SUCURSAL]
            new:
                item_permission: [ROLE_SUCURSAL]
            show:
                item_permission: [ROLE_SUCURSAL]
            delete:
                item_permission: [ROLE_SUCURSAL]
            search:
                item_permission: [ROLE_SUCURSAL]
            form:

                   