easy_admin:
    entities:
        Equipo:
            class: App\Entity\Equipo
            templates:
                # Twig namespace template syntax
                show: 'Equipo/show.html.twig'
            list:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
                filters:
                    - property: 'codigo'
                    - property: 'descripcion'
                    - property: 'cliente'
                fields:
                    - { property: 'codigo' }
                    - { property: 'descripcion' }
                    - { property: 'cliente' }
                actions:
                    - { name: 'show',  icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'remove', label: '' }
            edit:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
            new:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
            show:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
                fields:
                    - { property: 'codigo' }
                    - { property: 'descripcion' }
                    - { property: 'cliente' }
            delete:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
            search:
                item_permission: [ROLE_ADMIN, ROLE_ENCARGADO]
            form:
                fields:
                    - { property: 'codigo' }
                    - { property: 'descripcion' }
                    - { property: 'cliente' }