easy_admin:
    entities:
        Equipo:
            class: App\Entity\Equipo
            list:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
                filters:
                    - property: 'codigo'
                    - property: 'descripcion'
                fields:
                    - { property: 'codigo' }
                    - { property: 'descripcion' }
            edit:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
            new:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
            show:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
            delete:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
            search:
                item_permission: [ROLE_CLIENTE_CRUD, ROLE_ORDEN_TRABAJO]
            form:
                fields:
                    - { property: 'codigo' }
                    - { property: 'descripcion' }