easy_admin:
    entities:
        formulariosResultados:
            class: App\Entity\FormularioResultado
            list:
                item_permission: [ROLE_FORMULARIO]
                fields: ['id', 'nombre', 'titulo']
            edit:
                item_permission: [ROLE_FORMULARIO]
            new:
                item_permission: [ROLE_FORMULARIO]
            show:
                item_permission: [ROLE_FORMULARIO]
            delete:
                item_permission: [ROLE_FORMULARIO]
            search:
                item_permission: [ROLE_FORMULARIO]
            form:
                item_permission: [ROLE_FORMULARIO]
               
