easy_admin:
    entities:
        Item:
            class: App\Entity\Item
            controller: App\Controller\ItemController
            templates:
                # Twig namespace template syntax
                new: 'Item/new.html.twig'
                edit: 'Item/edit.html.twig'
            list:
                item_permission: [ROLE_ADMIN] 
                filters:
                    - property: 'nombre'
                    - property: 'titulo'
                    - property: 'descripcion'
                    - property: 'tipo'
                    - property: 'opciones'
                fields: ['id', 'nombre', 'titulo', 'descripcion', 'tipo']
            edit:
                item_permission: [ROLE_ADMIN] 
            new:
                item_permission: [ROLE_ADMIN] 
            show:
                item_permission: [ROLE_ADMIN] 
            delete:
                item_permission: [ROLE_ADMIN] 
            search:
                item_permission: [ROLE_ADMIN] 
            form:
                item_permission: [ROLE_ADMIN]
                fields:
                    - { type: 'group', columns: 6 }
                    - { property: 'nombre' }
                    - { property: 'tipo', type: 'choice', type_options: { choices: '%TIPO_ITEMS%' }}
                    - { type: 'group', columns: 6 }
                    - { property: 'titulo'}
                    - { property: 'descripcion'}
                    - { type: 'group', columns: 12, label: 'Opciones'  }
                    -
                        property: 'opciones'
                        label: false
                        type: 'collection'
                        type_options:
                            entry_type: App\Form\OpcionType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
