easy_admin:
    entities:
        Modulo:
            class: App\Entity\Modulo
            controller: App\Controller\ModuloController
            templates:
                # Twig namespace template syntax
                new: 'Modulo/new.html.twig'
                edit: 'Modulo/edit.html.twig'
            list:
                item_permission: [ROLE_ADMIN]
                filters:
                    - property: 'nombre'
                    - property: 'titulo'
                    - property: 'propiedadItems'
                fields: ['id', 'nombre', 'titulo']
                actions:
                    - { name: 'agregarDependencias', label: 'ver dependencias' }
            edit:
                item_permission: [ROLE_ADMIN]
            new:
                item_permission: [ROLE_ADMIN]
            show:
                item_permission: [ROLE_ADMIN]
            delete:
                item_permission: [ROLE_ADMIN]
            search:
                item_permission: [ROLE_ADMIN]
            form:
                item_permission: [ROLE_ADMIN]
                fields:
                    - { type: 'group', columns: 12 }
                    - { property: 'nombre', columns: 6 }
                    - { property: 'titulo', columns: 6}
                    - { type: 'group', columns: 12, label: 'Items'  }
                    -
                        property: 'propiedadItems'
                        label: false
                        type: 'collection'
                        type_options:
                            entry_type: App\Form\PropiedadItemType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
                            attr: {'class': 'col-md-12 '}
                        class: 'col-md-12'
                        form_group_class: 'col-md-12'
