easy_admin:
    entities:
        OrdenTrabajoCliente:
            class: App\Entity\OrdenTrabajo
            controller: App\Controller\OrdenTrabajoController
            templates:
                # Twig namespace template syntax
                new:  'OrdenTrabajo/new.html.twig'
                edit: 'OrdenTrabajo/edit.html.twig'
                show: 'OrdenTrabajo/show.html.twig'
                list: 'OrdenTrabajoCliente/list.html.twig'
            disabled_actions: ['edit', 'new', 'delete','show']
            list:
                item_permission: [ROLE_CLIENTE]
                batch_actions: ['exportar']

                filters:
                    - property: 'user'
                    - property: 'fecha'
                    - property: 'motivo'
                    - property: 'estado'
                      type: 'App\Form\Filter\EstadoFilterType'
                      mapped: false
                fields:
                    - id
                    - { property: 'estadoGestion', template: 'OrdenTrabajoCliente/estadoGestion.html.twig' }
                    #- { property: 'solicitud.nroIncidencia', label: 'Incidencia' }
                    - { property: 'user', type: 'text', label: 'Tecnico'}
                    #- { property: 'sucursal', type: 'text'}
                    - { property: 'estado', label: 'Estado', template: 'OrdenTrabajo/estado.html.twig'  }
                    - { property: 'fecha', format: 'd/m/Y' }
                    #- { property: 'horaInicio', format: 'H:i' }
                    #- { property: 'horaFin', format: 'H:i' }
                    #- { property: 'cliente', type: 'string', label: 'Sucursal'}
                    - { property: 'SucursalDeCliente',  label: 'Sucursal'}
                    #- { property: 'motivo', label: 'Postergado por' }
                actions:
                    - { name: 'show',  icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'remove', label: '' }
            show:
                item_permission: [ROLE_CLIENTE, ROLE_EMPLEADO]
                fields:
                    - { property: 'id', columns: 6 }
                    - { property: 'user',label: 'Tecnico', type: 'text', columns: 6 }
                    - { property: 'cliente', type: 'text', columns: 6 }
                    - { property: 'SucursalDeCliente', type: 'text', columns: 6 }
                    - { property: 'estadoToString', label: 'Estado', columns: 6 }
                    #- { property: 'horaInicio', columns: 6, format: 'H:i' }
                    #- { property: 'horaFin', columns: 6, format: 'H:i' }
                    - { property: 'fechaCompleta', columns: 6 }
                    - { property: 'motivo', columns: 6, label: 'Postergado por' }
                    - { property: 'createdAt', label: 'Creado', columns: 6, format: 'd/m/Y H:i' }
                    - { property: 'imageName', type: 'image', label: 'Firma', base_path: 'uploads/imagenes/resultado/', columns: 6 }
                    - { property: 'responsableFirma', label: 'Firma del responsable', columns: 6 }
                    - { property: 'comentario' }
                actions: ['-edit', '-delete', 'list']
            new:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - '-estado'
                    - { property: 'cliente', type: 'easyadmin_autocomplete', type_options: { attr: { required: true, create: true } }, columns: 12 }
            form:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - { type: 'group', label: 'Information', css_class: 'col-md-8'}
                    - { property: 'formulario', css_class: 'col-md-8', type_options: { required: true } }
                    - { property: 'orden', css_class: 'col-md-4' }
                    - { property: 'servicio', css_class: 'col-md-4' }
                    - { property: 'sucursal', type_options: { required: true }, permission: ROLE_ENCARGADO }
                    - { property: 'user', label: 'user', type_options: { required: true } }
                    - { property: 'cliente', type: 'easyadmin_autocomplete', type_options: { attr: { required: true, create: true } } }
                    - { property: 'comentario' }
                    - { property: 'estado', type: 'choice', type_options: { choices: '%otEstadoArray%' } }
                    - { type: 'group', label: 'Date', css_class: 'col-md-4' }
                    - { property: 'fecha', type_options: { widget: 'single_text', required: true } }
                    - { property: 'horaDesde', columns: 6, format: 'H:i', type_options: { widget: 'single_text', required: true } }
                    - { property: 'horaHasta', columns: 6, format: 'H:i', type_options: { widget: 'single_text', required: true } }
                    - { property: 'solicitudOpcion', type: 'hidden', type_options: { mapped: false } }
