easy_admin:
    entities:
        OrdenTrabajoSuc:
            class: App\Entity\OrdenTrabajo
            controller: App\Controller\OrdenTrabajoController
            templates:
                # Twig namespace template syntax
                new:  'OrdenTrabajo/new.html.twig'
                edit: 'OrdenTrabajo/edit.html.twig'
                show: 'OrdenTrabajo/show.html.twig'
                list: 'OrdenTrabajo/list.html.twig'
            list:
                max_results: 30
                item_permission: [ROLE_ENCARGADO, ROLE_SUCURSAL]
                batch_actions: ['exportar','delete']

                filters:
                    - property: 'user'
                    - property: 'formulario'
                    - property: 'sucursal'
                    - property: 'cliente'
                    - property: 'Facility'
                    - property: 'SucursalDeCliente'
                    - property: 'fecha'
                    - property: 'motivo'
                    - property: 'horaFin'
                    - property: 'estadosGestion'
                      type: 'App\Form\Filter\EstadosGestionFilterType'
                      mapped: false
                    - property: 'estado'
                      type: 'App\Form\Filter\EstadoFilterType'
                      mapped: false
                fields:
                    - 'id'
                    #- { property: 'solicitud.nroIncidencia', label: 'Incidencia' }
                    - { property: 'estadoGestion', template: 'OrdenTrabajo/estadoGestion.html.twig' }
                    - { property: 'formulario', type: 'text'}
                    - { property: 'user', type: 'text'}
                    - { property: 'sucursal', type: 'text'}
                    - { property: 'estado', label: 'Estado', template: 'OrdenTrabajo/estado.html.twig'  }
                    - { property: 'fecha', format: 'd/m/Y' }
                    - { property: 'horaInicio', format: 'H:i' }
                    - { property: 'horaFin', format: 'd/m/Y H:i' }
                    #- { property: 'formularioResultado.minutosTrabajado', format: 'H:i', label: 'Minutos trabajados' }
                    - { property: 'cliente', type: 'string' }
                    - { property: 'SucursalDeCliente', type: 'text', columns: 6 }
                    - { property: 'Facility', type: 'text', columns: 6 }                    
                    # - { property: 'motivo', label: 'Postergado por' }
                actions:
                    - { name: 'show',  icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' , permission: [ROLE_ADMIN] }
                    - { name: '-edit', icon: 'pencil', label: '' , permission: [ROLE_SUCURSAL] }
                    - { name: 'delete', icon: 'remove', label: '' }
            show:
                item_permission: [ROLE_ENCARGADO, ROLE_SUCURSAL]
                fields:
                    - { property: 'id', columns: 6 }
                    - { property: 'user', type: 'text', columns: 6 }
                    - { property: 'formulario', type: 'text', columns: 6 }
                    - { property: 'orden', columns: 6 }
                    - { property: 'sucursal', type: 'text', columns: 6 }
                    - { property: 'cliente', type: 'text', columns: 6 }
                    - { property: 'Comentario', type: 'text', columns: 6 }
                    - { property: 'SucursalDeCliente', type: 'text', columns: 6 }
                    - { property: 'Facility', type: 'text', columns: 6 }
                    - { property: 'estadoToString', label: 'Estado', columns: 6 }
                    - { property: 'horaInicio', columns: 6, format: 'd/m/Y H:i' }
                    - { property: 'horaFin', columns: 6, format: 'd/m/Y H:i' }
                    - { property: 'fechaCompleta', columns: 6 }
                    - { property: 'motivo', columns: 6, label: 'Postergado por' }
                    - { property: 'createdAt', label: 'Creado', columns: 6, format: 'd/m/Y H:i' }
                    #- { property: 'solicitud.servicio', label: 'Solicitud asociada', columns: 6 }
                    - { property: 'imageName', type: 'image', label: 'Firma', base_path: 'uploads/imagenes/resultado/', columns: 6 }
                    - { property: 'responsableFirma', label: 'Firma del responsable', columns: 6 }
                    - { property: 'comentario' }
                    - { property: 'firma' , label: 'Ultima Edicion de Formulario'}
                actions: [ 'delete', 'list', 'edit']
            new:
                item_permission: [ROLE_ENCARGADO, ROLE_SUCURSAL]
                fields:
                    - '-estado'
                    - { property: 'SucursalDeCliente' }
                    - { property: 'cliente', type_options: {required: false} ,columns: 12 , css_class: 'invisible' }
                    - { property: 'Facility', type_options: {required: false} , columns: 12 , css_class: 'invisible' }
                    - { property: 'user', label: 'Tecnico asignado' , type_options: { required: true }}
                    #- { property: 'cliente', type: 'easyadmin_autocomplete', type_options: { attr: { required: true, create: true } }, columns: 12 }
            edit:
                item_permission: [ROLE_ADMIN]
                fields:
                    - { property: 'SucursalDeCliente', label: 'Sucursal de Cliente' }
                    - { property: 'horaInicio', columns: 7, format: 'H:i', type_options: { widget: 'single_text', required: false }, label: 'Hora de inicio (NO EDITAR)' }
                    - { property: 'horaFin', columns: 7, format: 'H:i', type_options: { widget: 'single_text', required: true } }
                    - { property: 'minutos', label: 'Minutos Trabajados', type: 'integer' ,type_options: { mapped: false},css_class: 'invisible' }
                    - { property: 'imageFile', type: 'vich_image', css_class: 'my_image_form' }
            delete:
                item_permission: [ROLE_ENCARGADO]
            form:
                item_permission: [ROLE_ENCARGADO]
                fields:
                    - { type: 'group', label: 'Information', css_class: 'col-md-8'}
                    - { property: 'estadoGestion', type: 'choice', type_options: { choices: '%otEstadoGestionArray%' }, permission: [ROLE_ADMIN]}
                    - { property: 'SucursalDeCliente', label: 'Sucursal de Cliente', type_options: { attr: { required: true, create: true } } }
                    - { property: 'formulario', css_class: 'col-md-8', type_options: { required: true } }
                    - { property: 'user', label: 'Tecnico asignado' }
                    - { property: 'orden', css_class: 'col-md-4' }
                    - { property: 'servicio', css_class: 'col-md-4' }
                    - { property: 'sucursal', type_options: { required: true }, permission: [ROLE_ADMIN] }
                    - { property: 'comentario' }
                    - { property: 'estado', type: 'choice', type_options: { choices: '%otEstadoArray%' } }
                    - { type: 'group', label: 'Date', css_class: 'col-md-4' }
                    - { property: 'fecha', type_options: { widget: 'single_text', required: true } }
                    - { property: 'horaDesde', columns: 6, format: 'H:i', type_options: { widget: 'single_text', required: true } }
                    - { property: 'horaHasta', columns: 6, format: 'H:i', type_options: { widget: 'single_text', required: true } }
                    - { property: 'solicitudOpcion', type: 'hidden', type_options: { mapped: false } }
                    - { property: 'cliente', type_options: { attr: { required: true, create: true } }  }                   
                    - { property: 'Facility', label: 'Facility' }
                    - { property: 'imageFile', type: 'vich_image', css_class: 'my_image_form' }