easy_admin:
    entities:
        PropiedadItem:
            class: App\Entity\PropiedadItem
            list:
                item_permission: [ROLE_ADMIN]
            edit:
                item_permission: [ROLE_ADMIN]
            new:
                item_permission: [ROLE_ADMIN]
            show:
                item_permission: [ROLE_ADMIN]
            delete:
                item_permission: [ROLE_ADMIN]
            search:
                item_permission: [ROLE_ADMIN]