easy_admin:
    entities:
        Solicitud:
            class: App\Entity\Solicitud
            controller: App\Controller\SolicitudController
            templates:
                list: 'Solicitud/list.html.twig'
                new: 'Solicitud/new.html.twig'
                edit: 'Solicitud/edit.html.twig'
            list:
                item_permission: [ROLE_ENCARGADO,ROLE_CLIENTE]
                actions:
                    - { name: generarOt }
                filters:
                    - property: 'cliente'
                    - property: 'estado'
                    - property: 'servicio'
                    - property: 'necesitasAyuda'
                    - property: 'ordenTrabajo'
                    - property: 'nroIncidencia'
                    - { property: 'numeroSucursal', label: 'Nro. de Sucursal'}
                    - { property: 'direccionSucursal', label: 'Dirección de Sucursal'}
                    - { property: 'pisoSector', label: 'Piso de Sector'}
                    #- { property: 'fechaCompromiso' }
                fields:
                    - id
                    #- { property: 'fechaCompromiso', format: 'd/m/Y H:i' }
                    - { property: 'servicio', type: 'text' }
                    - { property: 'cliente', type: 'text' }
                    - { property: 'SucursalDeCliente' }
                    - { property: 'facility', label: ' Datos de Facility' }
                    - { property: 'nroIncidencia', label: ' Incidencia Nro' }
                    - { property: 'numeroSucursal', label: ' Nro sucursal' }
                    - { property: 'estado', label: 'Estado' ,template: 'Solicitud/estado.html.twig' }
                    - necesitasAyuda
                    
            edit:
                item_permission: [ROLE_ADMIN,ROLE_SUCURSAL,ROLE_CLIENTE]
            new:
                item_permission: [ROLE_ADMIN,ROLE_SUCURSAL,ROLE_CLIENTE]
            show:
                item_permission: [ROLE_ADMIN,ROLE_SUCURSAL,ROLE_CLIENTE]
            delete:
                item_permission: [ROLE_ENCARGADO, ROLE_FACILITY]
            search:
                item_permission: [ROLE_ENCARGADO,ROLE_CLIENTE]
            form:
                fields:
                    - { type: 'group', columns: 6 }
                    - { property: 'sucursal',label: 'Sucursal de Hogar', permission: ROLE_ADMIN }
                    - { property: 'cliente', permission: ROLE_ADMIN }
                    - { property: 'estado', permission: ROLE_ADMIN, type: 'choice', type_options: { choices: '%solicitudEstadoArray%' } }
                    - { 
                        property: 'servicio',
                        type: 'entity',
                        type_options: { class: 'App\Entity\Servicio', query_builder: 'App\Repository\SolicitudRepository::finByActivo' }
                     }
                    - { property: 'necesitasAyuda' }
                    - { property: 'Facility', permission: [ ROLE_ADMIN]}
                    - { property: 'SucursalDeCliente' , permission: [ROLE_FACILITY, ROLE_ADMIN], label: 'Sucursal'}
                    - { property: 'consulta', label: 'Cual es el problema?' }
                    - { property: 'imageFile', type: 'vich_image', css_class: 'my_image_form' }
                    - { type: 'group', columns: 6 }
                    - { property: 'nroIncidencia' }
                    #- { property: 'numeroSucursal', label: 'Número Sucursal' }
                    #- { property: 'direccionSucursal', label: 'Dirección Sucursal' }
                    - { property: 'pisoSector', label: 'Piso/Sector afectado' }
                    - 
                        property: 'fechaCompromiso'
                        label: 'Fecha de compromiso de solución'
                        permission: ROLE_ADMIN
                        type_options:
                            attr:
                                data-inputmask: "'alias': 'datetime', 'inputFormat': 'dd/mm/yyyy HH:MM'"
                            widget: 'single_text'
                            format: 'dd/MM/yyyy HH:mm'
