easy_admin:
  entities:
    SucursalDeCliente:
      class: App\Entity\SucursalDeCliente
      list:
        item_permission: [ROLE_PROPIEDAD_ITEM, ROLE_CLIENTE]
        fields:
          - id
          - codigo
          - direccion
          - { property: 'Cliente', type: 'text' }
          - facility
      edit:
        item_permission: [ROLE_CLIENTE]
        fields:
          - codigo
          - direccion
          - { property: 'Cliente' }
          - facility
          - Sucursal
      new:
        item_permission: [ROLE_PROPIEDAD_ITEM]
        fields:
          - codigo
          - direccion
          - { property: 'Cliente' }
          - facility
      show:
        item_permission: [ROLE_CLIENTE]
        fields:
          - id
          - direccion
          - codigo
          - { property: 'Cliente', type: 'text' }
      delete:
        item_permission: [ROLE_PROPIEDAD_ITEM]
      search:
        item_permission: [ROLE_PROPIEDAD_ITEM]
