easy_admin:
  entities:
    SucursalDeCliente:
      class: App\Entity\SucursalDeCliente
      list:
        item_permission: [ROLE_ADMIN, ROLE_CLIENTE]
        filters:
          - { property: 'id', label: 'ID' }
          - { property: 'codigo' }
          - { property: 'Sucursal', label: 'Sucursal de hogar' }
          - property: 'Cliente'
          - property: 'facility'
                 
        fields:
          - id
          - codigo
          - direccion
          - { property: 'Sucursal', label: 'Sucursal de hogar' }
          - { property: 'Cliente', type: 'text' }
          - facility
          # Debug, coordenadas geográficas
          - Latitud
          - Longitud
      edit:
        item_permission: [ROLE_CLIENTE]
        fields:
          - codigo
          - direccion
          - { property: 'Cliente' }
          - facility
          - Sucursal
          - Latitud
          - Longitud
      new:
        item_permission: [ROLE_ADMIN]
        fields:
          - codigo
          - direccion
          - { property: 'Cliente' }
          - facility
          - Sucursal
          - Latitud
          - Longitud
      show:
        item_permission: [ROLE_CLIENTE]
        fields:
          - id
          - direccion
          - codigo
          - { property: 'Cliente', type: 'text' }
      delete:
        item_permission: [ROLE_ADMIN]
      search:
        item_permission: [ROLE_ADMIN]
