easy_admin:
    entities:
        sucursaldecliente:
            class: App\Entity\SucursalDeCliente
            disabled_actions: ['new', 'delete']
            list:
                item_permission: [ROLE_ADMIN, ROLE_CLIENTE]
                fields:
                    - id
                    - codigo
                    - { property: 'Cliente', type: 'text'}
                    - users
            edit:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - codigo
                    - direccion
            new:
                item_permission: [ROLE_ADMIN]
            show:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - id
                    - codigo
                    - Cliente
                    - users
            delete:
                item_permission: [ROLE_ADMIN]
            search:
                item_permission: [ROLE_ADMIN]