easy_admin:
    entities:
        sucursaldecliente:
            class: App\Entity\SucursalDeCliente
            templates:
                show: 'SucursalDeCliente/find.html.twig'
            disabled_actions: ['new', 'delete', 'edit']
            list:
                item_permission: [ROLE_ADMIN, ROLE_CLIENTE]
                fields:
                    - id
                    - { property: 'codigo', label: 'Código' }
                    - { property: 'Cliente', type: 'text' }
            edit:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - { property: codigo, label: 'Código' }
                    - { property: direccion, label: 'Dirección' }
            new:
                item_permission: [ROLE_ADMIN]
            show:
                item_permission: [ROLE_CLIENTE]
                fields:
                    - { property: codigo, label: 'Código'}
                    - { property: direccion, label: 'Dirección'}
                    - { property: Cliente, type: 'string'}
            delete:
                item_permission: [ROLE_ADMIN]
            search:
                item_permission: [ROLE_ADMIN]