easy_admin:
    entities:
        UserCliente:
            class: App\Entity\UserCliente
            implements: App\Entity\iClienteFilter
            controller: App\Controller\UserController
            templates:
                # Twig namespace template syntax
                edit: 'User/edit.html.twig'
            disabled_actions: ['new', 'delete']
            list:
                item_permission: [ROLE_USER_CRUD, ROLE_STAFF]
                filters:
                    - property: 'username'
                    - property: 'email'
                    - property: 'enabled'
                fields: ['id', 'username', 'email', 'enabled', 'lastLogin', 'facility','street']
            edit:
                item_permission: [ROLE_USER_CRUD, ROLE_STAFF]
                fields:
                    - { property: 'username', columns: 6 }
                    - { property: 'email', columns: 6 }
                    - { property: 'sucursal', columns: 6 }
                    - { property: 'cliente', columns: 6 }
                    - { property: 'groups', columns: 6 }
                    # - { property: 'lastLogin', columns: 6 }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, columns: 6 }
                    - { property: 'enabled', columns: 6 }
                    -
                        property: 'roles'
                        type: 'choice'
                        columns: 6
                        type_options:
                            multiple: true
                            expanded: true
                            choices: '%LISTA_ROLES%'
                form_options: { validation_groups: ['Default', 'Profile'] }
            show:
                item_permission: [ROLE_USER_CRUD]
            delete:
                item_permission: [ROLE_USER_CRUD]
            search:
                item_permission: [ROLE_USER_CRUD]
