easy_admin:
    entities:
        UserCliente:
            class: App\Entity\UserCliente
            controller: App\Controller\UserController
            disabled_actions: [ 'new', 'delete']
            templates:
                # Twig namespace template syntax
                new:  'User/new.html.twig'
                edit: 'User/edit.html.twig'
            list:
                item_permission: [ROLE_USER_CRUD, ROLE_STAFF]
                filters:
                    - property: 'username'
                    - property: 'Facility'
                    - property: 'email'
                    - property: 'enabled'
                fields: ['id', 'username', 'email','SucursalDeCliente', 'Facility' , 'enabled', 'lastLogin']
            edit:
                item_permission: [ROLE_USER_CRUD, ROLE_STAFF]
                fields:
                    - { property: 'username', columns: 6 }
                    - { property: 'email', columns: 6 }
                    - { property: 'Facility', columns: 6 , permission: [ROLE_MANAGER]}
                    - { property: 'SucursalDeCliente', columns: 6 , permission: [ROLE_FACILITY]}
                    # - { property: 'lastLogin', columns: 6 }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, columns: 6 }
                    - { property: 'enabled', columns: 6 }
                form_options: { validation_groups: ['Default', 'Profile'] }
            show:
                item_permission: [ROLE_USER_CRUD]
            delete:
                item_permission: [ROLE_USER_CRUD]
            search:
                item_permission: [ROLE_USER_CRUD]
