easy_admin:
    entities:
        RecycleGroup:
            class: App\Entity\Group
            controller: App\Controller\Recycle\RecycleGroupController
            disabled_actions: ['edit', 'new']
            list:
                title: "Grupos Eliminados"
                item_permission: [ROLE_ADMIN]
                filters: [
                    { property: 'name', label: 'Nombre' },
                    { property: 'descripcion' }
                    ]
                fields:
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'descripcion' }
                    - { property: 'roles', template: 'group/role_list_field.html.twig' }
            new:
                item_permission: [ROLE_ADMIN]
            edit:
                item_permission: [ROLE_ADMIN]
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                item_permission: [ROLE_ADMIN]
                fields: 
                    - { type: 'group', columns: 12, label: 'Detalles' }
                    - { property: 'name', label: 'Nombre', columns: 4 }
                    - { property: 'descripcion', columns: 8 }
                    - { type: 'group', columns: 12, label: 'Secciones' }
                    -
                        property: 'roles'
                        label: 'Roles'
                        columns: 6
                        type: 'choice'
                        type_options:
                            multiple: true
                            expanded: true
                            choices: '%LISTA_ROLES%'
            show:
                item_permission: [ROLE_ADMIN]
                fields:
                    - { property: 'name', label: 'Nombre', columns: 6 }
                    - { property: 'descripcion', columns: 6 }
                    - { property: 'roles', label: 'Roles', columns: 6, template: 'group/role_list_field.html.twig' }
            delete:
                item_permission: [ROLE_ADMIN]
            search:
                item_permission: [ROLE_ADMIN]