easy_admin:
    entities:
        RecyclePais:
            class: App\Entity\Pais
            controller: App\Controller\Recycle\RecyclePaisController
            disabled_actions: ['edit', 'new']
            list:
                title: "Paises Eliminados"
                item_permission: [ROLE_PAIS]
                filters:
                    - property: 'nombre'
                fields: ['id', 'nombre']
            edit:
                item_permission: [ROLE_PAIS]
            new:
                item_permission: [ROLE_PAIS]
            show:
                item_permission: [ROLE_PAIS]
            delete:
                item_permission: [ROLE_PAIS]
            search:
                item_permission: [ROLE_PAIS]
