easy_admin:
    entities:
        RecycleServicio:
            class: App\Entity\Servicio
            disabled_actions: ['edit', 'new']
            controller: App\Controller\Recycle\RecycleServicioController
            filters:
                - property: 'titulo'
                - property: 'descripcion'
                - property: 'activo'
            list:
                title: "Servicios Eliminados"
                item_permission: [ROLE_ENCARGADO]
                fields:
                    - id
                    - titulo
                    - activo
            show:
                item_permission: [ROLE_ENCARGADO]
                fields:
                    - id
                    - titulo
                    - descripcion
                    - activo
                    - { property: 'image', type: 'image', base_path: '/uploads/imagenes/servicio' }
            edit:
                item_permission: [ROLE_ENCARGADO]
            new:
                item_permission: [ROLE_ENCARGADO]
            delete:
                item_permission: [ROLE_ENCARGADO]
            search:
                item_permission: [ROLE_ENCARGADO]
            form:
                fields:
                    - { property: 'titulo' }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
                    - { property: 'imageFile', type: 'vich_image', css_class: 'my_image_form' }
