easy_admin:
    entities:
        RecycleUser:
            class: App\Entity\User
            controller: App\Controller\Recycle\RecycleUserController
            templates:
                # Twig namespace template syntax
                new:  'User/new.html.twig'
                edit: 'User/edit.html.twig'
            disabled_actions: ['edit', 'new']
            list:
                title: "Usuarios Eliminados"
                item_permission: [ROLE_USER_CRUD]
                filters:
                    - property: 'username'
                    - property: 'email'
                    - property: 'enabled'
                    - property: 'sucursal'
                    - property: 'cliente'
                    - property: 'roles'
                fields: ['id', 'username', 'email', 'enabled', 'sucursal', 'lastLogin', 'roles']
            edit:
                item_permission: [ROLE_USER_CRUD]
                fields:
                    - { property: 'username', columns: 6 }
                    - { property: 'email', columns: 6 }
                    - { property: 'sucursal', columns: 6 }
                    - { property: 'cliente', columns: 6 }
                    - { property: 'groups', columns: 6 }
                    # - { property: 'lastLogin', columns: 6 }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, columns: 6 }
                    - { property: 'enabled', columns: 6 }
                    -
                        property: 'roles'
                        type: 'choice'
                        columns: 6
                        type_options:
                            multiple: true
                            expanded: true
                            choices: '%LISTA_ROLES%'
                form_options: { validation_groups: ['Default', 'Profile'] }
            new:
                item_permission: [ROLE_USER_CRUD]
                fields:
                    - { property: 'username', columns: 6 }
                    - { property: 'email', columns: 6 }
                    - { property: 'sucursal', columns: 6 }
                    - { property: 'cliente', columns: 6 }
                    - { property: 'groups', columns: 6 }
                    # - { property: 'lastLogin', columns: 6 }
                    - { property: 'plainPassword', type: 'text', type_options: { required: true }, columns: 6 }
                    - { property: 'enabled', columns: 6 }
                    -
                        property: 'roles'
                        type: 'choice'
                        columns: 6
                        type_options:
                            multiple: true
                            expanded: true
                            choices: '%LISTA_ROLES%'
                form_options: { validation_groups: ['Default', 'Registration'] }
            show:
                item_permission: [ROLE_USER_CRUD]
            delete:
                item_permission: [ROLE_USER_CRUD]
            search:
                item_permission: [ROLE_USER_CRUD]
